### ISSUE TITLE
Finally getting to code review

### ISSUE THREAD

**Issue by postfalk** [tnc-ca-geo/animl-base#12]
Hi Natty,

That looks straightforward and simple and I would like to keep it as simple as possible. 

One remark regarding the double storing of images into two S3 locations. I would not burden the RPi with two image pushes. Is there a way to have the lambda function reacts to the archive push and generate the hashed and thumb-nailed versions as well as the data extract. 

This would be even better in terms of keeping the RPi app light-weight.

Falk

**Comment by nathanielrindlaub** [comment]
Yeah we can definitely have the lambda do that work.

FYI as you look through the code, I haven't incorporated any of what we discussed earlier this week (storing images via hash in S3, archive bucket, thumbnail generation, allowing incomplete metadata to be stored in DB, deployment routing and assumptions...). I'll get to all of that when I'm done with the functional flows updates.

**Comment by postfalk** [comment]
Yes, I saw this. Please don't feel criticized. The good thing about that is that I would not recommend to implement all that on the base station. Just because you might want to re-use all that from other sources as well. So the base station would just dump the image to a S3 bucket and anything else would happen from there.

In that case, we could actually dump any image in the same bucket (even from AWS CLI uploads) and the pipeline would just work.

Falk

**Comment by nathanielrindlaub** [comment]
Ok cool, yeah I like that approach.

And no I don't feel criticized I just didn't want you to think I had ignored all that stuff we talked about! Fire away I'll take all the feedback I can get.
