### ISSUE TITLE
Look into opportunities to reduce Pi power consumption 

### ISSUE THREAD

**Issue by nathanielrindlaub** [tnc-ca-geo/animl-base#14]
The whole base station ran out of power surprisingly fast when I first set it up (Pi on AC) and charged it solely from the 50w solar panel. So I've done a bit of home testing and found that:
- When connected to DC output on the UPS, the UPS can last **~48 hrs without charge**.
- When connected to AC that the UPS drains completely in **22 hrs**
- 12 hrs of direct sunlight on the 50 w panel will charge the UPS from **0% to 65%**

This weekend I'll set the whole thing back up but drawing on DC and hopefully it will be able to sustain itself, but Falk had some ideas for reducing power draw on the Pi:
1. Make sure firmware is up to date https://www.geeks3d.com/20191101/raspberry-pi-4-new-firmware-reduces-power-consumption-and-boards-temperatures/
2. Look into SSD feature to reduce consumption
3. figure out whether the UPS cuts the USB power off when it cannot deliver a minimum voltage

**Comment by postfalk** [comment]
Thanks Natty, 

3. Will not reduce power but make sure that it comes back up after running into the ground at a series of dark days.

**Comment by nathanielrindlaub** [comment]
Other settings to reduce power consumption: 

https://www.jeffgeerling.com/blogs/jeff-geerling/raspberry-pi-zero-conserve-energy

**Comment by nathanielrindlaub** [comment]
Try using one of Gary's RPi 3B's and boot from USB flash drive 

https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/msd.md

https://www.raspberrypi.org/documentation/installation/installing-images/README.md

**Comment by nathanielrindlaub** [comment]
Looks like the RPi 3B consumes considerably less power at idle than the RPi 4 (~.33 amps vs ~.92 amps). I will follow up with a timed UPS drain test soon.

**Comment by nathanielrindlaub** [comment]
It took **>5.5 days (134 hours)** to drain the UPS completely with the new RPi 3B + usb flash drive setup (powered over USB cable from UPS' 2.1 amp DC USB port). There are still opportunities for gaining efficiency (shutting off WIFI if we don't use it, shutting off HDMI port, LED lights, going fully headless, etc.) but I'm going to close this out for now.
